### PR TITLE
Subscribe to infobase data via Global Registry.

### PR DESCRIPTION
**Pull request by twinge**
For now this only handles creates/updates from infobase and only stores values for fields that SMT cares about.

@jbirdjavi

### CODE REVIEW

**Comment by jbirdjavi** [comment]
Woot!  A few questions...
I'm guessing we're not worrying about authentication at this point since SM will only get notified by GR and then SM will pull the data from GR itself.  A fake notification would still result in real data being pulled down.
Also, it doesn't look like a whole lot of error handling is going on at this point...  (Error results in reraising the exception).  Could a pull from GR be shunted over to sidekiq and have sidekiq do retries in case of an error?  Also thinking backwards, what happens if GR sends a notification but SM is down for some reason?  Does GR retry later?

**Comment by twinge** [comment]
Auth: yeah, not really worrying about it since as you said, little harm can come from additional pulls.

Processing error/retry: that's a really good point. i'll switch it to using sidekiq to process

GR error/retry: yes, GR is using sidekiq and will retry if it gets anything other than a 200 response from SM

**Comment by twinge** [comment]
@jbirdjavi Uses sidekiq now. Anything else before i merge?

**Comment by jbirdjavi** [comment]
:+1:

**Pull request merged**
